FORMAT: 1A
HOST: http://{authentication-service-base-uri}/api

# Authentication Service
Methods for authentication

## Authenticate Token [/authentication/accesstoken]

### Authenticates an access token [GET]
Method to authenticates an access token.
+ Response 200 (application/json)

        {
            {
                "userId":"x123",
                "firstName": "John",
                "lastName": "Doe",
                "roles": "admin"
            }
        }
 
 
+ Response 401 

    Authentication failed
        
        
## Authenticate User [/authentication/user]

### Authenticates a user  [POST]
Method to authenticate an user.

+ userId (string)
+ password (string)

+ Request (application/json)

    {
        {
            "userId": "x123",
            "password": "*****"
        }
    }
    
+ Response 201 (application/json)

    + Headers

        Location: /authentication/user

    + Body

        {
            {
                "accessToken":"",
            }
        }
        

+ Response 403 

        Wrong password


+ Response 404 

        No user found with the specified user id.