FORMAT: 1A
HOST: http://{caretaker-service-base-uri}/api

# Caretaker Service

## Authentication
This API uses JSON Web Tokens for its authentication.

The parameters that are needed to be sent for this type of authentication are as follows:
+ `JWTHeaderName`
+ `JWTAcquireURL`
+ `JWTDestroyURL`

## Appointment [/appointments/{appointment_id}]

+ Parameters
    + appointment_id: 1 (required, string) - ID of the Appointment in form of a string
 
+ Attributes (NewAppointment)
    + appointmentId: 1 (string, optional)

### Retrieve a single Appointment [GET]
+ Request (application/json)
    + Headers

        authorization: Bearer JWT
        
+ Response 200 (application/json)

   + Attributes (Appointment)
   
+ Request XML (application/xml)
    + Headers

        authorization: Bearer JWT 

+ Response 200 (application/xml)
    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <appointment>
                <appointmentId>1</appointmentId>
                <contractId>1</contractId>
                <contractorsName>X</contractorsName>
                <roomNumber>A1</roomNumber>
                <issue>Issue</issue>
                <priorityLevel>low</priorityLevel>
                <date>2017-11-19</date>
                <appointmentType>moveIn</appointmentType>
            </appointment>  
            
+ Response 401 
    Missing/invalid access token or role not valid for the operation

+ Response 404 
    No appointment found with the specified ID
 
 
 
        
## Accept Appointment [/appointments/{appointment_id}/acceptance]

+ Parameters
    + appointment_id: 1 (required, string) - ID of the Appointment in form of a string

### Accept an  Appointment [PUT]
Method to accept a partucular appointment. An appointment can only be confirmed no later than two weeks after it's creation. Users only with Resident role can invoke this method.
+ Request (application/json)
    + Headers

        authorization: Bearer JWT

+ Response 201 (application/json)

+ Response 400 

        Validation failed

+ Response 401 

        Missing/invalid access token or role not valid for the operation

+ Response 404 

        No contract found with the specified ID
        
        
        
        
## Appointments Collection [/appointments{?date,pageNum,pageSize}]
Collection of all Appointments

+ Attributes (array[Appointment])

### List all Appointments [GET]
Method to retrieve multiple appointments. Use allowed query parameters to filter and pagination. Users with Administrator, Caretaker and Resident roles can invoke this method.

+ Parameters
   + date (string, optional) - Date to filter
   
   + pageNum (integer, optional) - Page number for the pagination
        + Default: 1 (only if pageSize is present)
        
   + pageSize (integer, optional) - Page size for the pagination.
        + Default: 20 (only if pageNum is present)
        
      
+ Request (application/json)
    + Headers

        authorization: Bearer JWT  

+ Response 200 (application/json)

    + Attributes (Appointments Collection)

+ Request XML (application/xml)
    + Headers

        authorization: Bearer JWT 
        
+ Response 200 (application/xml)
    + Body

            <?xml version="1.0" encoding="UTF-8"?>
            <appointments>
                <appointment>
                    <appointmentId>1</appointmentId>
                    <contractId>1</contractId>
                    <contractorsName>X</contractorsName>
                    <roomNumber>A1</roomNumber>
                    <issue>Issue</issue>
                    <priorityLevel>low</priorityLevel>
                    <date>2017-11-19</date>
                    <appointmentType>moveIn</appointmentType>
                <appointment>
            </appointments> 
            
            
+ Response 401 

        Missing/invalid access token or role not valid for the operation  
        
        
        
### Create a New Appointment [POST]
Method to add a new appoinment. Users only with Resident role can invoke this method. Move In appoinntment can only be added only after the confirmation of the contract. Move Out appointment can only be added no earlier than three months before the contract's current end date.

+ Attributes (NewAppointment)
        
+ Request (application/json)
    + Headers

        authorization: Bearer JWT 

+ Response 201 (application/json)

    + Attributes (Appointment)
    
+ Request XML (application/xml)
    + Headers

        authorization: Bearer JWT 

+ Response 201 (application/xml)

    + Body

            <?xml version="1.0" encoding="UTF-8"?>
                <appointment>
                    <appointmentId>1</appointmentId>
                    <contractId>1</contractId>
                    <contractorsName>X</contractorsName>
                    <roomNumber>A1</roomNumber>
                    <issue>Issue</issue>
                    <priorityLevel>low</priorityLevel>
                    <date>2017-11-19</date>
                    <appointmentType>moveIn</appointmentType>
                <appointment>
            
+ Response 400 

        Validation failed


+ Response 401 

        Missing/invalid access token or role not valid for the operation




+ Response 404 

        No appointment found with the specified id    
        
# Data Structures

## NewAppointment (object)


### Properties
+ contractId: 1 (string, optional) 
+ contractorsName: X (string, optional) 
+ roomNumber: A1 (string, optional) 
+ issue: Issue (string, optional) 
+ priorityLevel: low (enum[string], optional) 
    + `low`
    + `normal`
    + `high`
+ date: 2017-11-19 (string, optional) 
+ appointmentType: moveIn (enum[string], optional) 
    + `moveIn`
    + `moveOut`
    + `miscellaneous`