version: '3'

services:
  db:
    build: 
      context: database/
    ports:
      - "3306:3306"
    networks:
      - tuntuni

  authentication:
    build:
      context: .
      dockerfile: ./services/authentication/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - tuntuni

  contract:
    build:
      context: .
      dockerfile: ./services/contract/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
      - authentication
    networks:
      - tuntuni

  appointment:
    build:
      context: .
      dockerfile: ./services/appointment/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
      - authentication
      - contract
    networks:
      - tuntuni

  clientapp:
    build:
      context: client-app/
    ports:
      - "80:4200"
    depends_on:
      - db
      - authentication
      - contract
    networks:
      - tuntuni

networks:

  tuntuni:
    driver: bridge