version: '3'

services:
  db:
    build: 
      context: database/
    ports:
      - "3306:3306"
    network_mode: host

  authentication:
    build:
      context: .
      dockerfile: ./services/authentication/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    network_mode: host

  contract:
    build:
      context: .
      dockerfile: ./services/contract/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
      - authentication
    network_mode: host

  appointment:
    build:
      context: .
      dockerfile: ./services/appointment/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
      - authentication
      - contract
    network_mode: host

  clientapp:
    build:
      context: client-app/
    ports:
      - "4200:4200"
    depends_on:
      - db
      - authentication
      - contract
      - appointment
    network_mode: host
