-- MySQL Script generated by MySQL Workbench
-- Sat Dec 28 18:04:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectRestApi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS projectRestApi ;

-- -----------------------------------------------------
-- Schema projectRestApi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS projectRestApi DEFAULT CHARACTER SET utf8 ;
USE projectRestApi ;

-- -----------------------------------------------------
-- Table projectRestApi.appointment
-- -----------------------------------------------------
DROP TABLE IF EXISTS projectRestApi.appointment ;

CREATE TABLE IF NOT EXISTS projectRestApi.appointment (
  appointmentId VARCHAR(100) NOT NULL,
  contractorsName VARCHAR(45) NULL,
  contractId VARCHAR(45) NULL,
  roomNumber VARCHAR(45) NULL,
  appointmentType ENUM('MoveIn', 'MoveOut', 'Miscellaneous') NULL,
  issue VARCHAR(250) NULL,
  desiredDate DATE NULL,
  status ENUM('Accepted', 'Denied', 'Received') NULL,
  priority ENUM('Low', 'Normal', 'High') NULL,
  createdBy VARCHAR(45) NULL,
  createdOn DATE NULL,
  PRIMARY KEY (appointmentId))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
