-- MySQL Script generated by MySQL Workbench
-- Tue Dec 10 15:38:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjectRestApi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProjectRestApi` ;

-- -----------------------------------------------------
-- Schema ProjectRestApi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjectRestApi` DEFAULT CHARACTER SET utf8 ;
USE `ProjectRestApi` ;

-- -----------------------------------------------------
-- Table `ProjectRestApi`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectRestApi`.`contract` ;

CREATE TABLE IF NOT EXISTS `ProjectRestApi`.`contract` (
  `idcontract` INT NOT NULL AUTO_INCREMENT,
  `startdate` DATETIME NULL,
  `creationdate` DATETIME NULL,
  `status` TINYINT(1) NULL,
  `enddate` DATETIME NULL,
  `apartment` VARCHAR(45) NULL,
  PRIMARY KEY (`idcontract`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectRestApi`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectRestApi`.`users` ;

CREATE TABLE IF NOT EXISTS `ProjectRestApi`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `firstname` VARCHAR(500) NOT NULL,
  `middlename` VARCHAR(500) NOT NULL,
  `lastname` VARCHAR(500) NOT NULL,
  `email` VARCHAR(100) NULL,
  `contactno` VARCHAR(100) NULL,
  `currenttenentstatus` TINYINT(1) NULL,
  `address` TEXT NULL,
  `contract_idcontract` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_contract1_idx` (`contract_idcontract` ASC) VISIBLE,
  CONSTRAINT `fk_users_contract1`
    FOREIGN KEY (`contract_idcontract`)
    REFERENCES `ProjectRestApi`.`contract` (`idcontract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectRestApi`.`apartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectRestApi`.`apartment` ;

CREATE TABLE IF NOT EXISTS `ProjectRestApi`.`apartment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roomno` VARCHAR(45) NULL,
  `block` VARCHAR(45) NULL,
  `roomsize` VARCHAR(45) NULL,
  `street` VARCHAR(1000) NULL,
  `buildingno` INT NULL,
  `zipcode` INT NULL,
  `city` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `idApartmentMapping`
    FOREIGN KEY (`id`)
    REFERENCES `ProjectRestApi`.`contract` (`idcontract`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectRestApi`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectRestApi`.`appointment` ;

CREATE TABLE IF NOT EXISTS `ProjectRestApi`.`appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `RequesterID` INT NOT NULL,
  `title` VARCHAR(200) NULL,
  `description` VARCHAR(2000) NULL,
  `createdate` DATETIME NULL,
  `assignedto` INT NULL,
  `priority` ENUM('LOW', 'HIGH', 'MEDIUM') NULL,
  `assignedgroup` ENUM('HOUSEMASTER', 'MAINTAINER', 'GENETOR', 'MANAGER', 'SUPERADMIN') NULL DEFAULT 'HOUSEMASTER',
  `status` ENUM('ACCEPTED', 'REJECTED', 'SOLVED', 'PENDING', 'WITHDRAW') NULL DEFAULT 'PENDING',
  `enddate` DATETIME NULL,
  `contract_idcontract` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idAppointmentMapping_idx` (`RequesterID` ASC) VISIBLE,
  INDEX `fk_appointment_contract1_idx` (`contract_idcontract` ASC) VISIBLE,
  CONSTRAINT `idAppointmentMapping`
    FOREIGN KEY (`RequesterID`)
    REFERENCES `ProjectRestApi`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_appointment_contract1`
    FOREIGN KEY (`contract_idcontract`)
    REFERENCES `ProjectRestApi`.`contract` (`idcontract`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectRestApi`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectRestApi`.`admin` ;

CREATE TABLE IF NOT EXISTS `ProjectRestApi`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `group` ENUM('HOUSEMASTER', 'MAINTAINER', 'GENETOR', 'MANAGER', 'SUPERADMIN') NOT NULL,
  `name` VARCHAR(200) NULL,
  `contactno` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectRestApi`.`auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectRestApi`.`auth` ;

CREATE TABLE IF NOT EXISTS `ProjectRestApi`.`auth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` VARCHAR(100) NULL,
  `password` VARCHAR(1000) NULL,
  `hash` VARCHAR(200) NULL,
  `salt` VARCHAR(200) NULL,
  `authkey` VARCHAR(500) NULL,
  `lastlogin` DATETIME NULL,
  INDEX `idMapping_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `idMapping`
    FOREIGN KEY (`id`)
    REFERENCES `ProjectRestApi`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idmapping`
    FOREIGN KEY (`id`)
    REFERENCES `ProjectRestApi`.`admin` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjectRestApi`.`adminContractApartmentRel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProjectRestApi`.`adminContractApartmentRel` ;

CREATE TABLE IF NOT EXISTS `ProjectRestApi`.`adminContractApartmentRel` (
  `AdminID` INT NOT NULL,
  `contractID` INT NOT NULL,
  `apartmentID` INT NOT NULL,
  INDEX `Admin_idx` (`AdminID` ASC) VISIBLE,
  INDEX `Contract_idx` (`contractID` ASC) VISIBLE,
  INDEX `Apartment_idx` (`apartmentID` ASC) VISIBLE,
  CONSTRAINT `Admin`
    FOREIGN KEY (`AdminID`)
    REFERENCES `ProjectRestApi`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Contract`
    FOREIGN KEY (`contractID`)
    REFERENCES `ProjectRestApi`.`contract` (`idcontract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Apartment`
    FOREIGN KEY (`apartmentID`)
    REFERENCES `ProjectRestApi`.`apartment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
