openapi: 3.0.0

info:
  title: Authentication Service
  version: 1.0.0 

servers:
  - url: http://{authentication-service-base-uri}/api

tags:
  - name: authentication
    description: Methods for authentication

paths:

  /authentication/user:
    post:
      tags:
        - authentication
      summary: Authenticates a user
      description: Method to authenticate an user.
      requestBody:
        description: User credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        403:
          description: Wrong password
        404:
          description: No user found with the specified user id.
      security:
      - bearerAuth: []
  
  /authentication/accesstoken:
    get:
      tags:
        - authentication
      summary: Authenticates an access token
      description: Method to authenticates an access token.
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        401:
          description: Authentication failed
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      properties:
        userId:
          type: string
        password:
          type: string
            
      xml:
        name: LoginRequest

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
            
      xml:
        name: LoginResponse
        
    User:
      type: object
      properties:
        userId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        roles:
          type: array
          items:
            type: string
            
      xml:
        name: User
